apiVersion: v1
data:
  DB_PASSWORD: {{ .Values.website.secret.password | quote }}
kind: Secret
metadata:
  name: {{ .Values.website.secret.fullname | quote }}
  namespace: {{ .Values.namespace | quote }}
type: Opaque
