apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.website.service.fullname  |  quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  selector:
    app: ecomm-app
  ports:
    - protocol: TCP
      port: {{ .Values.website.port | default 80 }}
      targetPort: {{ .Values.website.port  | default 80 }}
  type: LoadBalancer
