name: Build and push docker image to GCR
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: |
        gcloud auth configure-docker

    - name: Install gke-gcloud-auth-plugin
      run: |
        sudo apt-get install google-cloud-cli-gke-gcloud-auth-plugin

    #- name: Create GKE cluster
    #  run: |
    #    gcloud container clusters create kubernetes-cluster --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Update kube config
      run: gcloud container clusters get-credentials kubernetes-cluster --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy go-app helm chart to GKE
      run: |
        helm uninstall helm-app -n helm
        cd kubernetes/helm-app
        helm install helm-app helm-app -f values.yaml . -n helm